# Generated by Django 3.0.2 on 2020-01-21 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studentg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redressal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daytoken', models.IntegerField(default=studentg.models.Grievance.increment_daytoken)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=10)),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('University', 'University'), ('Institute', 'Institute'), ('Department', 'Department')], max_length=15)),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance', to='redressal.Redressal_Body')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Sub_Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'daytoken')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=1000)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='studentg.Grievance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
