# Generated by Django 3.0.2 on 2020-01-18 12:48

from django.db import migrations, models
import django.db.models.deletion
import studentg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daytoken', models.IntegerField(default=studentg.models.Grievance.increment_daytoken)),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.CharField(choices=[('UNI', 'University'), ('INS', 'Institute'), ('DEP', 'Department')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'unique_together': {('date', 'daytoken')},
            },
        ),
    ]
