# Generated by Django 3.0.8 on 2020-07-17 13:32

from django.db import migrations


def correct_choices(apps, schema_editor):
    status_dct = {'Pending': 2, 'Resolved': 4}
    Grievance = apps.get_model('studentg', 'Grievance')
    for gr in Grievance.objects.all():
        gr.status_new = status_dct[gr.status]
        gr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0002_auto_20200717_1859'),
    ]

    operations = [
        migrations.RunPython(correct_choices),
    ]
