# Generated by Django 3.0.2 on 2020-03-17 07:49

from django.db import migrations, models
import studentg.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0002_auto_20200317_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='daytoken',
            field=models.IntegerField(default=studentg.models.DayToken.get_new_token, editable=False),
        ),
    ]
