# Generated by Django 3.0.8 on 2020-07-17 13:39

from django.db import migrations


def correct_choices(apps, schema_editor):
    category_dct = {
        'University': 1,
        'Institute': 2,
        'Department': 3,
    }
    Grievance = apps.get_model('studentg', 'Grievance')
    for gr in Grievance.objects.all():
        gr.category_new = category_dct[gr.category]
        gr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0003_correct_choices'),
    ]

    operations = [
        migrations.RunPython(correct_choices),
    ]
