# Generated by Django 3.0.2 on 2020-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0003_auto_20200317_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='daytoken',
            field=models.IntegerField(),
        ),
    ]
