# Generated by Django 3.0.8 on 2020-07-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0004_correct_choices2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Grievance',
            name='status'
        ),
        migrations.RenameField(
            model_name='Grievance',
            old_name='status_new',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='Grievance',
            name='category'
        ),
        migrations.RenameField(
            model_name='Grievance',
            old_name='category_new',
            new_name='category',
        ),
    ]
