# Generated by Django 3.0.8 on 2020-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0005_correct_choices3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'University'), (2, 'Institute'), (3, 'Department')]),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'In Review'), (3, 'Pending'), (4, 'Resolved'), (5, 'Rejected')], default=2),
        ),
    ]
