# Generated by Django 3.0.8 on 2020-07-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0006_auto_20200717_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['date_time']},
        ),
    ]
