# Generated by Django 3.0.8 on 2020-08-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentg', '0011_auto_20200802_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='grievance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='studentg.Grievance'),
        ),
    ]
