# Generated by Django 3.0.2 on 2020-01-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redressal', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('UNI', 'University'), ('INS', 'Institute'), ('DEP', 'Department'), ('UNI_H', 'University_H'), ('INS_H', 'INSTITUTE_H'), ('DEP_H', 'Department_H')], max_length=15)),
                ('uidb64', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Redressal_Body')),
            ],
        ),
    ]
