# Generated by Django 3.0.2 on 2020-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='designation',
            field=models.CharField(choices=[('ST', 'Student'), ('UNI', 'University'), ('INS', 'Institute'), ('DEP', 'Department'), ('UNI_H', 'University_H'), ('INS_H', 'INSTITUTE_H'), ('DEP_H', 'Department_H')], max_length=15),
        ),
    ]
