# Generated by Django 3.0.8 on 2020-07-17 13:29

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('accounts', '0002_auto_20200607_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
