# Generated by Django 3.0.8 on 2020-07-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200607_1303'),
    ]

    operations = [
        
    ]
