# Generated by Django 3.0.2 on 2020-01-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_student_temp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='sys_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
