# Generated by Django 3.0.2 on 2020-06-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedressalBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_type', models.CharField(choices=[('UNI', 'University'), ('INS', 'Institute'), ('DEP', 'Department')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redressal_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='redressal.RedressalBody')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redressal_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='redressal.RedressalBody')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.University')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Institute')),
                ('redressal_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='redressal.RedressalBody')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=255)),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='redressal.RedressalBody')),
            ],
            options={
                'unique_together': {('sub_type', 'redressal_body')},
            },
        ),
    ]
