# Generated by Django 3.0.2 on 2020-01-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redressal_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Redressal_Body')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=255)),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Redressal_Body')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Redressal_Body')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.University')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Institute')),
                ('redressal_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redressal.Redressal_Body')),
            ],
        ),
    ]
