# Generated by Django 3.0.8 on 2020-07-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redressal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redressalbody',
            options={'verbose_name_plural': 'Redressal Bodies'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub categories'},
        ),
    ]
