# Generated by Django 3.0.8 on 2020-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redressal', '0002_auto_20200731_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
    ]
